-- Add three new PG listings with the provided names and locations
INSERT INTO public.pgs (
  name, 
  description, 
  location, 
  rent, 
  room_type, 
  gender, 
  rating, 
  review_count, 
  images, 
  amenities, 
  nearby_places, 
  pg_rules, 
  maintenance_fee, 
  security_deposit, 
  verified, 
  available, 
  featured,
  property_type,
  furnishing_status,
  balcony_count,
  bathroom_count,
  parking_available,
  meal_service,
  laundry_service,
  cleaning_service
) VALUES 
(
  'BLISS COED MANAYATA', 
  'Modern co-ed PG accommodation near Manyata Tech Park with comfortable double sharing rooms and essential amenities.',
  'Manyata, Bangalore', 
  12000, 
  'Double', 
  'Co-ed', 
  4.2, 
  15, 
  ARRAY['/lovable-uploads/74216825-4e78-4fac-a3dc-f0500d74fad6.png'], 
  ARRAY['WiFi', 'AC', 'Attached Bathroom', 'Wardrobe', 'Study Table', 'Chair'], 
  ARRAY['Manyata Tech Park - 1.5km', 'Metro Station - 2km', 'Shopping Mall - 1km'], 
  ARRAY['No smoking', 'No loud music after 10 PM', 'Visitors allowed till 9 PM', 'Keep common areas clean'], 
  1500, 
  25000, 
  true, 
  true, 
  true,
  'independent',
  'semi-furnished',
  0,
  1,
  true,
  true,
  true,
  true
),
(
  'COOL COED MANYATA', 
  'Premium co-ed PG with modern furnishing, wooden furniture and excellent amenities near Manyata Tech Park.',
  'Manyata, Bangalore', 
  15000, 
  'Double', 
  'Co-ed', 
  4.5, 
  28, 
  ARRAY['/lovable-uploads/e39b6b70-3d77-431d-8883-d1898310a029.png'], 
  ARRAY['WiFi', 'AC', 'Attached Bathroom', 'Wooden Furniture', 'Study Table', 'Chair', 'Wardrobe'], 
  ARRAY['Manyata Tech Park - 1km', 'Metro Station - 1.8km', 'Restaurants - 500m'], 
  ARRAY['No smoking', 'No loud music after 10 PM', 'Visitors allowed till 9 PM', 'Maintain cleanliness'], 
  2000, 
  30000, 
  true, 
  true, 
  true,
  'independent',
  'fully-furnished',
  0,
  1,
  true,
  true,
  true,
  true
),
(
  'CIA COED MANYATA', 
  'Spacious co-ed PG with common dining area, modern interiors and great city views near Manyata Tech Park.',
  'Manyata, Bangalore', 
  13500, 
  'Single', 
  'Co-ed', 
  4.3, 
  22, 
  ARRAY['/lovable-uploads/11232ab7-e437-43df-b52d-55cab3dfd2f7.png'], 
  ARRAY['WiFi', 'Common Dining Area', 'City View', 'Modern Furniture', 'Study Space', 'Cafeteria'], 
  ARRAY['Manyata Tech Park - 1.2km', 'Metro Station - 2.5km', 'Food Court - 300m'], 
  ARRAY['No smoking', 'No loud music after 10 PM', 'Visitors allowed till 8 PM', 'Use dining area respectfully'], 
  1800, 
  27000, 
  true, 
  true, 
  true,
  'independent',
  'fully-furnished',
  0,
  2,
  true,
  true,
  true,
  true
);